StartupEvents.registry("block", (event) => {
    event.create("raw_silver_block")
        .textureAll("kubejs:block/raw_silver_block")
        .material("metal")
        .hardness(5.0)
        .resistance(6.0)
        .requiresTool(true)
        .tagBlock("mineable/pickaxe")
        .tagBlock('minecraft:needs_iron_tool')

    event.create("silver_block")
        .textureAll("kubejs:block/silver_block")
        .material("metal")
        .hardness(5.0)
        .resistance(6.0)
        .requiresTool(true)
        .tagBlock("mineable/pickaxe")
        .tagBlock('minecraft:needs_iron_tool')
})