JEIEvents.information(event => {
    event.addItem('kubejs:candy_pancreas', Text.black({ "translate": "kubejs.jei.candy_pancreas.1" }))
    event.addItem('kubejs:fire_gem', Text.black({ "translate": "kubejs.jei.fire_gem.1" }))
    event.addItem('kubejs:magic_spine', Text.black({ "translate": "kubejs.jei.magic_spine.1" }))
    event.addItem('kubejs:magic_vision', Text.black({ "translate": "kubejs.jei.magic_vision.1" }))
    
    event.addItem(Ingredient.of('#kubejs:evolution'), [Text.black({ "translate": "kubejs.jei.evolution.1" })])
    event.addItem('kubejs:lucky_cookie_organ', Text.black({ "translate": "kubejs.jei.lucky_cookie_organ.1" }))
    event.addItem('kubejs:unholy_grail', Text.black({ "translate": "kubejs.jei.unholy_grail.1" }))
    event.addItem('kubejs:aesegull_rib_left', Text.black({ "translate": "kubejs.jei.aesegull_rib_left.1" }))
    event.addItem('kubejs:aesegull_rib_right', Text.black({ "translate": "kubejs.jei.aesegull_rib_right.1" }))
    event.addItem('kubejs:executioner_blade_pieces', Text.black({ "translate": "kubejs.jei.executioner_blade_pieces.1" }))
    event.addItem('kubejs:love_between_lava_and_ice', Text.black({ "translate": "kubejs.jei.love_between_lava_and_ice.1" }))
    event.addItem('kubejs:forbidden_fruit', Text.black({ "translate": "kubejs.jei.forbidden_fruit.1" }))
    event.addItem('kubejs:heavy_hammer_muscle', Text.black({ "translate": "kubejs.jei.heavy_hammer_muscle.1" }))
    event.addItem('kubejs:leviathan_spine', Text.black({ "translate": "kubejs.jei.leviathan_spine.1" }))
    event.addItem('kubejs:leviathan_rib', Text.black({ "translate": "kubejs.jei.leviathan_rib.1" }))
    event.addItem('kubejs:bone_soul', Text.black({ "translate": "kubejs.jei.bone_soul.1" }))
    event.addItem('kubejs:heart_of_blade', Text.black({ "translate": "kubejs.jei.heart_of_blade.1" }))
    event.addItem('kubejs:god_bless_empty_necklace', Text.black({ "translate": "kubejs.jei.god_bless_empty_necklace.1" }))
    event.addItem('kubejs:redstone_chipset', Text.black({ "translate": "kubejs.jei.redstone_chipset.1" }))
    event.addItem('kubejs:ore_lung', Text.black({ "translate": "kubejs.jei.ore_lung.1" }))
})