const resourceCount = 'resourceCount'
const resourceCountMax = 'resourceCountMax'
const defaultResourceMax = 100

const organActive = 'organActive'

const bossTypeList = [
    'somebosses:aesegull',
    'somebosses:prismarine_watcher',
    'somebosses:froverlord',
    'somebosses:volcanium',
    'somebosses:merciless_assasin',
    'somebosses:dark_mask',
    'somebosses:knight_garent',
    'somebosses:vulcan',
    'somebosses:ancient_wizard',
    'somebosses:man_of_water',
    'somebosses:flaming_berserker',
    'somebosses:electric_head',
    'somebosses:frost_magma',
    'somebosses:stone_guard',
    'somebosses:crimson_vampire',
    'somebosses:skeleton_demon',
    'somebosses:mono_eyed_skeleton',
    'somebosses:hand_head',
    'somebosses:ender_ordnance',
    'somebosses:nameless_one',
    'somebosses:sand_giant',
    "somebosses:rib_golem",
    'cataclysm:netherite_monstrosity',
    'cataclysm:ender_guardian',
    'cataclysm:ignis',
    'cataclysm:the_harbinger',
    'cataclysm:the_leviathan',
    'bosses_of_mass_destruction:void_blossom',
    'bosses_of_mass_destruction:lich',
    'bosses_of_mass_destruction:gauntlet',
    'bosses_of_mass_destruction:obsidilith',
    'meetyourfight:bellringer',
    'meetyourfight:rosalyne',
    'meetyourfight:swampjaw',
    'meetyourfight:dame_fortuna',
]

const bossesOfMassDestructionBossTypeList = [
    'bosses_of_mass_destruction:void_blossom',
    'bosses_of_mass_destruction:lich',
    'bosses_of_mass_destruction:gauntlet',
    'bosses_of_mass_destruction:obsidilith',
]
const worldOfBossTypeList = [
    'somebosses:aesegull',
    'somebosses:prismarine_watcher',
    'somebosses:froverlord',
    'somebosses:volcanium',
    'somebosses:merciless_assasin',
    'somebosses:dark_mask',
    'somebosses:knight_garent',
    'somebosses:vulcan',
    'somebosses:ancient_wizard',
    'somebosses:man_of_water',
    'somebosses:flaming_berserker',
    'somebosses:electric_head',
    'somebosses:frost_magma',
    'somebosses:stone_guard',
    'somebosses:crimson_vampire',
    'somebosses:skeleton_demon',
    'somebosses:mono_eyed_skeleton',
    'somebosses:hand_head',
    'somebosses:ender_ordnance',
    'somebosses:nameless_one',
    'somebosses:sand_giant',
    "somebosses:rib_golem",
]


const tumorAttriBute = [
    { name: 'chestcavity:filtration', muti: 1, max: 5 },
    { name: 'chestcavity:breath_recovery', muti: 0.5, max: 5 },
    { name: 'chestcavity:nutrition', muti: 1, max: 5 },
    { name: 'chestcavity:nerves', muti: 0.25, max: 5 },
    { name: 'chestcavity:strength', muti: 1, max: 5 },
    { name: 'chestcavity:health', muti: 1, max: 5 },
    { name: 'chestcavity:breath_capacity', muti: 0.5, max: 5 },
    { name: 'chestcavity:detoxification', muti: 1, max: 5 },
    { name: 'chestcavity:speed', muti: 0.25, max: 5 },
    { name: 'chestcavity:endurance', muti: 1, max: 5 },
    { name: 'chestcavity:luck', muti: 0.5, max: 5 },
    { name: 'chestcavity:defense', muti: 0.25, max: 5 },
    { name: 'chestcavity:digestion', muti: 1, max: 5 },
    { name: 'chestcavity:metabolism', muti: 1, max: 5 },
    { name: 'chestcavity:fire_resistant', muti: 0.5, max: 5 },
    { name: 'chestcavity:knockback_resistant', muti: 0.5, max: 5 },
    { name: 'chestcavity:water_breath', muti: 0.5, max: 5 },
]
