ServerEvents.tags('worldgen/structure', event => {
  event.add('kubejs:fortress_locator', 'minecraft:fortress')
  event.add('kubejs:graveyard', ['graveyard:altar', 'graveyard:crypt', 'graveyard:dead_tree', 'graveyard:giant_mushroom', 'graveyard:haunted_house', 'graveyard:large_graveyard', 'graveyard:lich_prison', 'graveyard:medium_graveyard', 'graveyard:memorial_tree', 'graveyard:mushroom_grave', 'graveyard:ruins', 'graveyard:small_desert_grave', 'graveyard:small_desert_graveyard', 'graveyard:small_grave', 'graveyard:small_graveyard', 'graveyard:small_mountain_grave', 'graveyard:small_savanna_grave', 'graveyard_biomes:mushroom_structure'])
})

ServerEvents.tags('item', event => {
  event.add('kubejs:rain_ritual', ['minecraft:apple', 'minecraft:golden_apple', 'minecraft:enchanted_golden_apple', 'create:honeyed_apple'])

  event.add('kubejs:isb_spell_book', ['irons_spellbooks:netherite_spell_book', 'irons_spellbooks:diamond_spell_book', 'irons_spellbooks:gold_spell_book', 'irons_spellbooks:iron_spell_book', 'irons_spellbooks:copper_spell_book', 'irons_spellbooks:rotten_spell_book', 'irons_spellbooks:blaze_spell_book', 'irons_spellbooks:dragonskin_spell_book', 'irons_spellbooks:druidic_spell_book',
    'irons_spellbooks:villager_spell_book', 'irons_spellbooks:blood_staff', 'irons_spellbooks:evoker_spell_book'])

  event.add('curios:body', ['supplementaries:quiver'])

  //肺部标签（用于处理尘肺）
  event.add('kubejs:lung', 'chestcavity:lung')
  event.add('kubejs:lung', 'chestcavity:rotten_lung')
  event.add('kubejs:lung', 'chestcavity:animal_lung')
  event.add('kubejs:lung', 'chestcavity:llama_lung')
  event.add('kubejs:lung', 'chestcavity:fireproof_lung')
  event.add('kubejs:lung', 'chestcavity:small_animal_lung')
  event.add('kubejs:lung', 'chestcavity:insect_lung')
  event.add('kubejs:lung', 'chestcavity:ender_lung')
  event.add('kubejs:lung', 'chestcavity:dragon_lung')
  event.add('kubejs:lung', 'chestcavity:saltwater_lung')
  event.add('kubejs:lung', 'chestcavity:gas_bladder')
  

  //肌肉标签
  event.add('kubejs:muscle', 'chestcavity:muscle')
  event.add('kubejs:muscle', 'chestcavity:rotten_muscle')
  event.add('kubejs:muscle', 'chestcavity:animal_muscle')
  event.add('kubejs:muscle', 'chestcavity:llama_muscle')
  event.add('kubejs:muscle', 'chestcavity:fireproof_muscle')
  event.add('kubejs:muscle', 'chestcavity:small_animal_muscle')
  event.add('kubejs:muscle', 'chestcavity:insect_muscle')
  event.add('kubejs:muscle', 'chestcavity:ender_muscle')
  event.add('kubejs:muscle', 'chestcavity:dragon_muscle')
  event.add('kubejs:muscle', 'chestcavity:saltwater_muscle')
  event.add('kubejs:muscle', 'chestcavity:aquatic_muscle')
  event.add('kubejs:muscle', 'chestcavity:small_aquatic_muscle')
  event.add('kubejs:muscle', 'chestcavity:piston_muscle')
  event.add('kubejs:muscle', 'chestcavity:fish_muscle')
  event.add('kubejs:muscle', 'chestcavity:small_fish_muscle')
  event.add('kubejs:muscle', 'chestcavity:brutish_muscle')
  event.add('kubejs:muscle', 'chestcavity:swift_muscle')
  event.add('kubejs:muscle', 'chestcavity:springy_muscle')
  event.add('kubejs:muscle', 'chestcavity:small_springy_muscle')

  //心脏标签
  event.add('kubejs:heart', 'chestcavity:heart')
  event.add('kubejs:heart', 'chestcavity:rotten_heart')
  event.add('kubejs:heart', 'chestcavity:animal_heart')
  event.add('kubejs:heart', 'chestcavity:llama_heart')
  event.add('kubejs:heart', 'chestcavity:fireproof_heart')
  event.add('kubejs:heart', 'chestcavity:small_animal_heart')
  event.add('kubejs:heart', 'chestcavity:insect_heart')
  event.add('kubejs:heart', 'chestcavity:ender_heart')
  event.add('kubejs:heart', 'chestcavity:dragon_heart')
  event.add('kubejs:heart', 'chestcavity:saltwater_heart')
  event.add('kubejs:heart', 'chestcavity:rabbit_heart')

  //野兽标签
  event.add('kubejs:beast', 'chestcavity:animal_lung')
  event.add('kubejs:beast', 'chestcavity:animal_muscle')
  event.add('kubejs:beast', "chestcavity:animal_heart")
  event.add('kubejs:beast', "chestcavity:animal_appendix")
  event.add('kubejs:beast', "chestcavity:animal_intestine")
  event.add('kubejs:beast', "chestcavity:animal_kidney")
  event.add('kubejs:beast', "chestcavity:animal_liver")
  event.add('kubejs:beast', "chestcavity:animal_rib")
  event.add('kubejs:beast', "chestcavity:animal_spine")
  event.add('kubejs:beast', "chestcavity:animal_spleen")
  event.add('kubejs:beast', "chestcavity:animal_stomach")
  event.add('kubejs:beast', 'chestcavity:brutish_muscle')
  event.add('kubejs:beast', 'chestcavity:swift_muscle')
  event.add('kubejs:beast', 'chestcavity:springy_muscle')
  event.add('kubejs:beast', 'chestcavity:small_springy_muscle')
  event.add('kubejs:beast', 'chestcavity:rabbit_heart')
  event.add('kubejs:beast', 'chestcavity:small_animal_lung')
  event.add('kubejs:beast', 'chestcavity:small_animal_muscle')
  event.add('kubejs:beast', "chestcavity:small_animal_heart")
  event.add('kubejs:beast', "chestcavity:small_animal_appendix")
  event.add('kubejs:beast', "chestcavity:small_animal_intestine")
  event.add('kubejs:beast', "chestcavity:small_animal_kidney")
  event.add('kubejs:beast', "chestcavity:small_animal_liver")
  event.add('kubejs:beast', "chestcavity:small_animal_rib")
  event.add('kubejs:beast', "chestcavity:small_animal_spine")
  event.add('kubejs:beast', "chestcavity:small_animal_spleen")
  event.add('kubejs:beast', "chestcavity:small_animal_stomach")

  event.add('kubejs:is_cookie', ['extradelight:apple_cookie', 'extradelight:gingerbread_cookie', 'extradelight:glow_berry_cookie', 'extradelight:sugar_cookie', 'extradelight:pumpkin_cookie', 'farmersdelight:honey_cookie', 'minecraft:cookie', 'farmersdelight:sweet_berry_cookie', 'extradelight:sugar_cookie_steve', 'extradelight:sugar_cookie_alex', 'extradelight:sugar_cookie_villager', 'extradelight:sugar_cookie_emerald', 'extradelight:sugar_cookie_pickaxe', 'extradelight:sugar_cookie_diamond', 'extradelight:sugar_cookie_sword', 'extradelight:sugar_cookie_creeper'])
  event.add('kubejs:is_cookie_block', ['extradelight:chocolate_chip_cookie_block_item', 'extradelight:gingerbread_cookie_block_item', 'extradelight:sweet_berry_cookie_block_item', 'extradelight:apple_cookie_block_item', 'extradelight:sugar_cookie_block_item', 'extradelight:pumpkin_cookie_block_item', 'extradelight:honey_cookie_block_item', 'extradelight:glow_berry_cookie_block_item'])
  event.add('forge:bones/dragon', ['iceandfire:dragonbone'])
  event.add('forge:bones/wither', ['iceandfire:witherbone'])
  event.add('biomancy:cannot_be_eaten_by_cradle', ['weaponmaster:wm_broadswordlarge', 'weaponmaster:wm_broadsword', 'weaponmaster:wm_rapier', 'weaponmaster:wm_rapierlarge'])
  event.add('iceandfire:scales/myrmex', ['iceandfire:myrmex_jungle_chitin', 'iceandfire:myrmex_desert_chitin'])
  event.add('iceandfire:scales/deathworm', ['iceandfire:deathworm_chitin_white', 'iceandfire:deathworm_chitin_red', 'iceandfire:deathworm_chitin_yellow'])
  event.add('iceandfire:dragon_food_meat', ['minecraft:rabbit', 'minecraft:cooked_rabbit', 'chestcavity:raw_butchered_meat', 'chestcavity:cooked_butchered_meat', 'chestcavity:raw_man_meat', 'chestcavity:cooked_man_meat', 'alexsmobs:kangaroo_meat', 'alexsmobs:cooked_kangaroo_meat', 'unusualprehistory:cooked_coty', 'unusualprehistory:raw_coty', 'unusualprehistory:cooked_mammoth', 'unusualprehistory:raw_mammoth', 'bookwyrms:book_wyrm_cooked', 'bookwyrms:book_wyrm_raw', 'unusualprehistory:cooked_stetha', 'unusualprehistory:raw_stetha', 'unusualprehistory:cooked_austro', 'unusualprehistory:raw_austro', 'unusualprehistory:raw_scau', 'unusualprehistory:cooked_scau', 'alexsmobs:cooked_catfish', 'alexsmobs:raw_catfish', 'minecraft:cod', 'minecraft:cooked_cod', 'minecraft:cooked_salmon', 'minecraft:salmon'])

  const baseorgan = event.get('chestcavity:salvageable').getObjectIds()
  baseorgan.forEach(organ => {
    event.add('kubejs:organ', organ)
  })
  
})